=== ekim197711/xml-xsd-xslt-wsdl/handsOnDag2DTD/værktøjskasseDefinition.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT værktøjskasse (værktøj+)>
<!ELEMENT værktøj (støjniveau, art, farver)>

<!ELEMENT støjniveau (#PCDATA)>
<!ATTLIST støjniveau enhed CDATA "decibel">

<!ELEMENT art (#PCDATA)>
<!ATTLIST art sprog (en|dk|sw|de) #REQUIRED>
<!ELEMENT farver (farve*)>
<!ELEMENT farve (#PCDATA)>

=== ekim197711/xml-xsd-xslt-wsdl/arkiv/handsOnDag2DTD/værktøjskasse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE værktøjskasse SYSTEM "værktøjskasseDefinition.dtd">
<værktøjskasse>
    <værktøj>
        <støjniveau enhed="kanonslag">14</støjniveau>
        <art sprog="dk">hammer</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
    </værktøj>
    <værktøj>
        <støjniveau enhed="decibel">5</støjniveau>
        <art sprog="en">sav</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
    </værktøj>
    <værktøj>
        <støjniveau>0</støjniveau>
        <art sprog="sw">skruetrækker</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
    </værktøj>
</værktøjskasse>

=== ekim197711/xml-xsd-xslt-wsdl/handsOnDag2DTD/værktøjskasse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE værktøjskasse SYSTEM "værktøjskasseDefinition.dtd">
<værktøjskasse>
    <værktøj>
        <art sprog="dk">hammer</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
        <støjniveau>14</støjniveau>
    </værktøj>
    <værktøj>
        <art sprog="en">sav</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
        <støjniveau enhed="decibel">5</støjniveau>
    </værktøj>
    <værktøj>
        <art sprog="sw">skruetrækker</art>
        <farver>
            <farve>rød</farve>
            <farve>blå</farve>
            <farve>sort</farve>
        </farver>
        <støjniveau>0</støjniveau>
    </værktøj>
</værktøjskasse>
