=== ekim197711/xml-xsd-xslt-wsdl/arkiv/handsOnDag2XslOgXPath/blomsterkrans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://minblomsterkrans"
        xmlns:bb="http://minblomsterkrans"
>
  <xs:element name="blomsterkrans" type="bb:blomsterkransType"/>
  <xs:complexType name="blomstType">
    <xs:sequence>
      <xs:element name="navn">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Solsikke"/>
            <xs:enumeration value="Rose"/>
            <xs:enumeration value="Karse"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="duftscore">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="7"/>
            <xs:enumeration value="8"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="placering">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="I haven i solen"/>
            <xs:enumeration value="I solen ved grillen"/>
            <xs:enumeration value="Indenfor i vat"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="blomsterkransType">
    <xs:sequence>
      <xs:element type="bb:blomstType" name="blomst" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ekim197711/xml-xsd-xslt-wsdl/arkiv/handsOnDag2XslOgXPath/blomsterkrans.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="file:///home/kursus/IdeaProjects/kursusxml/handsOnDag2XslOgXPath/blomsterkransTransform.xsl"
        version="2.0" ?>

<bb:blomsterkrans
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://minblomsterkrans blomsterkrans.xsd"
        xmlns:bb="http://minblomsterkrans"
>
    <bb:blomst>
        <bb:navn>Solsikke</bb:navn>
        <bb:duftscore>1</bb:duftscore>
        <bb:placering>I haven i solen</bb:placering>
    </bb:blomst>
    <bb:blomst>
        <bb:navn>Rose</bb:navn>
        <bb:duftscore>7</bb:duftscore>
        <bb:placering>I solen ved grillen</bb:placering>
    </bb:blomst>
    <bb:blomst>
        <bb:navn>Karse</bb:navn>
        <bb:duftscore>8</bb:duftscore>
        <bb:placering>Indenfor i vat</bb:placering>
    </bb:blomst>
</bb:blomsterkrans>
