=== ekim197711/xml-xsd-xslt-wsdl/20191119/fodbold/fodboldhold.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT fodboldhold (spiller*)>
<!ELEMENT spiller (navn, position, transfer)>
<!ELEMENT navn (#PCDATA)>
<!ATTLIST navn kÃ¦lenavn #REQUIRED>
<!ELEMENT position (#PCDATA)>
<!ATTLIST position minattr>
<!ELEMENT transfer (#PCDATA)>

=== ekim197711/xml-xsd-xslt-wsdl/20191119/fodbold/fodboldhold.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xml" href="fodboldhold.xslt"?>
<!--<!DOCTYPE fodboldhold SYSTEM "fodboldhold.dtd">-->
<fodboldhold>
    <spiller>
        <navn kælenavn="hurtigkarl">Allan Simonsen</navn>
        <position minattr="test1234">Forsvar</position>
        <transfer>100</transfer>
    </spiller>
    <spiller>
        <navn>Søren Lerby</navn>
        <position>Midterbane</position>
        <transfer>200</transfer>
    </spiller>
    <spiller>
        <navn kælenavn="den kære">Elkjær</navn>
        <position>Libero</position>
        <transfer>300</transfer>
    </spiller>
</fodboldhold>
