=== ekim197711/xml-xsd-xslt-wsdl/20191119/spilbutik/xsdeksempel/spilbutikkontrakt.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://mikesbutik.dk"
            xmlns:msb="http://mikesbutik.dk"
            elementFormDefault="qualified"
            attributeFormDefault="qualified"
>
    <xsd:element name="spilbutikken" type="msb:spilButikType"/>

    <xsd:complexType name="spilButikType">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="spil" type="msb:spilType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="spilType">
        <xsd:all>
            <xsd:element name="titel" type="xsd:string"/>
            <xsd:element name="score" type="xsd:int"/>
            <xsd:element name="pris" type="msb:prisType"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="prisType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:decimal">
                <xsd:attribute name="valuta" type="xsd:string"
                               use="required" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== ekim197711/xml-xsd-xslt-wsdl/20191119/spilbutik/xsdeksempel/spilbutik.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sb:spilbutikken
        xmlns:sb="http://mikesbutik.dk"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://mikesbutik.dk spilbutikkontrakt.xsd"
>
    <sb:spil>
        <sb:titel>Miss Pacman</sb:titel>
        <sb:score>4</sb:score>
        <!-- Jeg har rettet indholdet med CDATA sÃ¥ XML'en er wellformed -->
        <sb:pris sb:valuta="dkk">140.5</sb:pris>
    </sb:spil>
    <sb:spil>
        <sb:titel>Pacmanf dfsggffgfhghgh ghg dhg g hgh gh  ghgh d dgh</sb:titel>
        <sb:score>-50</sb:score>
        <sb:pris sb:valuta="euro">100.5</sb:pris>
    </sb:spil>
    <sb:spil>
        <sb:titel>Space Invaders</sb:titel>
        <sb:score>5</sb:score>
        <sb:pris sb:valuta="sek">99.99</sb:pris>
    </sb:spil>
</sb:spilbutikken>
