=== ekim197711/xml-xsd-xslt-wsdl/arkiv/kursusdag1dtd/spilbutik.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT spilbutik (spil*)>
<!ELEMENT spil (pris,navn, beskrivelse, score, platform)>
<!ELEMENT navn (#PCDATA)>
<!ELEMENT pris (#PCDATA)>
<!ELEMENT beskrivelse (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ATTLIST pris valuta (pund|lire|dollar) #REQUIRED>
<!ATTLIST pris medmoms CDATA #REQUIRED>

=== ekim197711/xml-xsd-xslt-wsdl/arkiv/kursusdag1dtd/spilbutik.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE spilbutik SYSTEM "spilbutik.dtd">
<spilbutik>
    <spil>
        <pris valuta="pund" medmoms="true">123.3</pris>
        <navn>Pacman</navn>
        <beskrivelse>test 123</beskrivelse>
        <score>4</score>
        <platform>commodore64</platform>
    </spil>
    <spil>
        <pris valuta="lire" medmoms="true">123.3</pris>
        <navn>WOW</navn>
        <beskrivelse>World of Warcraft 123</beskrivelse>
        <score>4</score>
        <platform>commodore64</platform>
    </spil>
</spilbutik>
