=== ekim197711/xml-xsd-xslt-wsdl/examplequalified/spilbutik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://mynamespace"
        xmlns="http://mynamespace">

    <xs:element name="spilbutik" type="spilbutikType"/>

  <xs:complexType name="spilbutikType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="spil" type="spilType"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="NavnMedAttributes" >
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>

    </xs:complexType>

    <xs:simpleType name="RestrictedNavn">
        <xs:restriction base="xs:string">
            <xs:minLength value="4"/>
            <xs:maxLength value="40"/>
        </xs:restriction>
    </xs:simpleType>

  <xs:complexType name="spilType">
    <xs:sequence>
      <xs:element name="navn">
          <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="RestrictedNavn">
                      <xs:attribute name="forkortelse"
                                    type="xs:string"
                                    use="required" />
                      <xs:attribute name="sprog"
                                    type="xs:string"
                                    use="required" />
                  </xs:extension>
              </xs:simpleContent>
          </xs:complexType>
      </xs:element>
      <xs:element name="score" type="xs:int"/>
      <xs:element name="beskrivelse" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ekim197711/xml-xsd-xslt-wsdl/demo1/spilbutik.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" version="2.0" href="spilbutik.xsl" ?>
<spilbutik
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="spilbutik.xsd">
    <spil>
        <navn forkortelse="pc" sprog="dk">Pacman</navn>
        <score>3</score>
        <beskrivelse>Spis oste pas på spøg.</beskrivelse>
    </spil>
    <spil>
        <navn forkortelse="si" sprog="dk">Space Invaders</navn>
        <score>5</score>
        <beskrivelse>Space shooter</beskrivelse>
    </spil>
    <spil>
        <navn forkortelse="jon" sprog="dk">Jones in the fast lane</navn>
        <score>3</score>
        <beskrivelse>Game of life</beskrivelse>
    </spil>
</spilbutik>

=== ekim197711/xml-xsd-xslt-wsdl/examplequalified/spilbutikVisning.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" version="2.0" href="file:///home/kursus/IdeaProjects/xmldemo1/examplequalified/spilbutikVisning.xsl"

        ?>
<sb:spilbutik
        xmlns:sb="http://mynamespace"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

        xsi:schemaLocation="
        http://mynamespace
        spilbutik.xsd">
    <sb:spil>
        <sb:navn forkortelse="pc" sprog="dk">Pacman</sb:navn>
        <sb:score>2</sb:score>
        <sb:beskrivelse>
            <!--<![CDATA[-->
        Spis oste pas på spøg.
        <!--]]>-->
        </sb:beskrivelse>
    </sb:spil>
    <sb:spil>
        <sb:navn forkortelse="si" sprog="dk">Space Invaders</sb:navn>
        <sb:score>5</sb:score>
        <sb:beskrivelse>Space shooter</sb:beskrivelse>
    </sb:spil>
    <sb:spil>
        <sb:navn forkortelse="jon" sprog="dk">Jones in the fast lane</sb:navn>
        <sb:score>3</sb:score>
        <sb:beskrivelse>Game of life</sb:beskrivelse>
    </sb:spil>
</sb:spilbutik>

=== ekim197711/xml-xsd-xslt-wsdl/examplecss/spilbutik.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="spilbutik.css"?>
<sb:spilbutik
        xmlns:sb="http://mynamespace"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        http://mynamespace
        file:///home/kursus/IdeaProjects/xmldemo1/exampledtd/spilbutik.xsd">
    <spil>
        <navn forkortelse="pc" sprog="dk">Pacman</navn>
        <score>3</score>
        <beskrivelse><![CDATA[
        Spis oste pas på spøg.<>
        ]]></beskrivelse>
    </spil>
    <spil>
        <navn forkortelse="si" sprog="dk">Space Invaders</navn>
        <score>5</score>
        <beskrivelse>Space shooter</beskrivelse>
    </spil>
    <spil>
        <navn forkortelse="jon" sprog="dk">Jones in the fast lane</navn>
        <score>3</score>
        <beskrivelse>Game of life</beskrivelse>
    </spil>
</sb:spilbutik>
